// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BASETYPESSERIALIZER_CORE_BASE_H_
#define FLATBUFFERS_GENERATED_BASETYPESSERIALIZER_CORE_BASE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Core {
namespace Base {

struct Vec2;

struct Vec3;

struct Vec4;

struct MapEntryInt;
struct MapEntryIntBuilder;

struct MapEntryFloat;
struct MapEntryFloatBuilder;

struct MapEntryVec2;
struct MapEntryVec2Builder;

struct MapEntryVec3;
struct MapEntryVec3Builder;

struct MapEntryVec4;
struct MapEntryVec4Builder;

struct MapEntryString;
struct MapEntryStringBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

struct MapEntryInt FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryIntBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyField<int32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct MapEntryIntBuilder {
  typedef MapEntryInt Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryInt::VT_KEY, key, 0);
  }
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(MapEntryInt::VT_VALUE, value, 0);
  }
  explicit MapEntryIntBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryInt> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryInt>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryInt> CreateMapEntryInt(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    int32_t value = 0) {
  MapEntryIntBuilder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

struct MapEntryFloat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryFloatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct MapEntryFloatBuilder {
  typedef MapEntryFloat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryFloat::VT_KEY, key, 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(MapEntryFloat::VT_VALUE, value, 0.0f);
  }
  explicit MapEntryFloatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryFloat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryFloat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryFloat> CreateMapEntryFloat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    float value = 0.0f) {
  MapEntryFloatBuilder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

struct MapEntryVec2 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryVec2Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  const Core::Base::Vec2 *value() const {
    return GetStruct<const Core::Base::Vec2 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyField<Core::Base::Vec2>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct MapEntryVec2Builder {
  typedef MapEntryVec2 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryVec2::VT_KEY, key, 0);
  }
  void add_value(const Core::Base::Vec2 *value) {
    fbb_.AddStruct(MapEntryVec2::VT_VALUE, value);
  }
  explicit MapEntryVec2Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryVec2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryVec2>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryVec2> CreateMapEntryVec2(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    const Core::Base::Vec2 *value = nullptr) {
  MapEntryVec2Builder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

struct MapEntryVec3 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryVec3Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  const Core::Base::Vec3 *value() const {
    return GetStruct<const Core::Base::Vec3 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyField<Core::Base::Vec3>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct MapEntryVec3Builder {
  typedef MapEntryVec3 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryVec3::VT_KEY, key, 0);
  }
  void add_value(const Core::Base::Vec3 *value) {
    fbb_.AddStruct(MapEntryVec3::VT_VALUE, value);
  }
  explicit MapEntryVec3Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryVec3> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryVec3>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryVec3> CreateMapEntryVec3(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    const Core::Base::Vec3 *value = nullptr) {
  MapEntryVec3Builder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

struct MapEntryVec4 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryVec4Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  const Core::Base::Vec4 *value() const {
    return GetStruct<const Core::Base::Vec4 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyField<Core::Base::Vec4>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct MapEntryVec4Builder {
  typedef MapEntryVec4 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryVec4::VT_KEY, key, 0);
  }
  void add_value(const Core::Base::Vec4 *value) {
    fbb_.AddStruct(MapEntryVec4::VT_VALUE, value);
  }
  explicit MapEntryVec4Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryVec4> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryVec4>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryVec4> CreateMapEntryVec4(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    const Core::Base::Vec4 *value = nullptr) {
  MapEntryVec4Builder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

struct MapEntryString FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapEntryStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint64_t key() const {
    return GetField<uint64_t>(VT_KEY, 0);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_KEY, 8) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct MapEntryStringBuilder {
  typedef MapEntryString Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint64_t key) {
    fbb_.AddElement<uint64_t>(MapEntryString::VT_KEY, key, 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(MapEntryString::VT_VALUE, value);
  }
  explicit MapEntryStringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapEntryString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapEntryString>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapEntryString> CreateMapEntryString(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  MapEntryStringBuilder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapEntryString> CreateMapEntryStringDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t key = 0,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return Core::Base::CreateMapEntryString(
      _fbb,
      key,
      value__);
}

}  // namespace Base
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_BASETYPESSERIALIZER_CORE_BASE_H_
