namespace Core.Base;

struct Uuid {
    low:ulong;
    high:ulong;
}

struct Vec2 {
    x:float;
    y:float;
}

struct Vec3 {
    x:float;
    y:float;
    z:float;
}

struct Vec4 {
    x:float;
    y:float;
    z:float;
    w:float;
}

table MapEntryInt {
    key:ulong;
    value:int32;
}

table MapEntryFloat {
    key:ulong;
    value:float;
}

table MapEntryVec2 {
    key:ulong;
    value:Vec2;
}

table MapEntryVec3 {
    key:ulong;
    value:Vec3;
}

table MapEntryVec4 {
    key:ulong;
    value:Vec4;
}

table MapEntryString {
    key:ulong;
    value:string;
}

table MapEntryUuid {
    key:ulong;
    value:Uuid;
}

struct Vertex {
    position:Vec3;
    normal:Vec3;
    tangent:Vec3;
    bitangent:Vec3;
    uv0:Vec2;
    uv1:Vec2;
    color:Vec4;
    blend_weights:Vec4;
    blend_indices:Vec4;
}

struct AABB {
    min:Vec3;
    max:Vec3;
}

struct Transform {
    position:Vec3;
    rotation:Vec4;
    scale:Vec3;
}