// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CAMERA_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_CAMERA_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct Camera;
struct CameraBuilder;

struct Camera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FOV = 4,
    VT_NEAR = 6,
    VT_FAR = 8
  };
  float fov() const {
    return GetField<float>(VT_FOV, 0.0f);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 0.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_FOV, 4) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           verifier.EndTable();
  }
};

struct CameraBuilder {
  typedef Camera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fov(float fov) {
    fbb_.AddElement<float>(Camera::VT_FOV, fov, 0.0f);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(Camera::VT_NEAR, near, 0.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(Camera::VT_FAR, far, 0.0f);
  }
  explicit CameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Camera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Camera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Camera> CreateCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float fov = 0.0f,
    float near = 0.0f,
    float far = 0.0f) {
  CameraBuilder builder_(_fbb);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_fov(fov);
  return builder_.Finish();
}

inline const Core::Serialization::Camera *GetCamera(const void *buf) {
  return ::flatbuffers::GetRoot<Core::Serialization::Camera>(buf);
}

inline const Core::Serialization::Camera *GetSizePrefixedCamera(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::Serialization::Camera>(buf);
}

inline bool VerifyCameraBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::Serialization::Camera>(nullptr);
}

inline bool VerifySizePrefixedCameraBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::Serialization::Camera>(nullptr);
}

inline void FinishCameraBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Camera> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCameraBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Camera> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_CAMERA_CORE_SERIALIZATION_H_
