// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CAMERASERIALIZER_CORE_H_
#define FLATBUFFERS_GENERATED_CAMERASERIALIZER_CORE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "BaseTypesSerializer_generated.h"

namespace Core {

struct CameraSerializer;
struct CameraSerializerBuilder;

struct CameraSerializer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraSerializerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FOV = 4,
    VT_NEAR = 6,
    VT_FAR = 8
  };
  float fov() const {
    return GetField<float>(VT_FOV, 0.0f);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 0.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_FOV, 4) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           verifier.EndTable();
  }
};

struct CameraSerializerBuilder {
  typedef CameraSerializer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fov(float fov) {
    fbb_.AddElement<float>(CameraSerializer::VT_FOV, fov, 0.0f);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(CameraSerializer::VT_NEAR, near, 0.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(CameraSerializer::VT_FAR, far, 0.0f);
  }
  explicit CameraSerializerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CameraSerializer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CameraSerializer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CameraSerializer> CreateCameraSerializer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float fov = 0.0f,
    float near = 0.0f,
    float far = 0.0f) {
  CameraSerializerBuilder builder_(_fbb);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_fov(fov);
  return builder_.Finish();
}

inline const Core::CameraSerializer *GetCameraSerializer(const void *buf) {
  return ::flatbuffers::GetRoot<Core::CameraSerializer>(buf);
}

inline const Core::CameraSerializer *GetSizePrefixedCameraSerializer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::CameraSerializer>(buf);
}

inline bool VerifyCameraSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::CameraSerializer>(nullptr);
}

inline bool VerifySizePrefixedCameraSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::CameraSerializer>(nullptr);
}

inline void FinishCameraSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::CameraSerializer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCameraSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::CameraSerializer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_CAMERASERIALIZER_CORE_H_
