// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMPONENT_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_COMPONENT_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct Component;
struct ComponentBuilder;

struct Camera;
struct CameraBuilder;

struct MeshRenderer;
struct MeshRendererBuilder;

enum ComponentData : uint8_t {
  ComponentData_NONE = 0,
  ComponentData_Camera = 1,
  ComponentData_MeshRenderer = 2,
  ComponentData_MIN = ComponentData_NONE,
  ComponentData_MAX = ComponentData_MeshRenderer
};

inline const ComponentData (&EnumValuesComponentData())[3] {
  static const ComponentData values[] = {
    ComponentData_NONE,
    ComponentData_Camera,
    ComponentData_MeshRenderer
  };
  return values;
}

inline const char * const *EnumNamesComponentData() {
  static const char * const names[4] = {
    "NONE",
    "Camera",
    "MeshRenderer",
    nullptr
  };
  return names;
}

inline const char *EnumNameComponentData(ComponentData e) {
  if (::flatbuffers::IsOutRange(e, ComponentData_NONE, ComponentData_MeshRenderer)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesComponentData()[index];
}

template<typename T> struct ComponentDataTraits {
  static const ComponentData enum_value = ComponentData_NONE;
};

template<> struct ComponentDataTraits<Core::Serialization::Camera> {
  static const ComponentData enum_value = ComponentData_Camera;
};

template<> struct ComponentDataTraits<Core::Serialization::MeshRenderer> {
  static const ComponentData enum_value = ComponentData_MeshRenderer;
};

bool VerifyComponentData(::flatbuffers::Verifier &verifier, const void *obj, ComponentData type);
bool VerifyComponentDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Component FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_TYPE = 4,
    VT_DATA = 6
  };
  Core::Serialization::ComponentData data_type() const {
    return static_cast<Core::Serialization::ComponentData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const Core::Serialization::Camera *data_as_Camera() const {
    return data_type() == Core::Serialization::ComponentData_Camera ? static_cast<const Core::Serialization::Camera *>(data()) : nullptr;
  }
  const Core::Serialization::MeshRenderer *data_as_MeshRenderer() const {
    return data_type() == Core::Serialization::ComponentData_MeshRenderer ? static_cast<const Core::Serialization::MeshRenderer *>(data()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyComponentData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Core::Serialization::Camera *Component::data_as<Core::Serialization::Camera>() const {
  return data_as_Camera();
}

template<> inline const Core::Serialization::MeshRenderer *Component::data_as<Core::Serialization::MeshRenderer>() const {
  return data_as_MeshRenderer();
}

struct ComponentBuilder {
  typedef Component Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_type(Core::Serialization::ComponentData data_type) {
    fbb_.AddElement<uint8_t>(Component::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Component::VT_DATA, data);
  }
  explicit ComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Component> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Component>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Component> CreateComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Core::Serialization::ComponentData data_type = Core::Serialization::ComponentData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  ComponentBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

struct Camera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FOV = 4,
    VT_NEAR = 6,
    VT_FAR = 8
  };
  float fov() const {
    return GetField<float>(VT_FOV, 0.0f);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 0.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_FOV, 4) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           verifier.EndTable();
  }
};

struct CameraBuilder {
  typedef Camera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fov(float fov) {
    fbb_.AddElement<float>(Camera::VT_FOV, fov, 0.0f);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(Camera::VT_NEAR, near, 0.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(Camera::VT_FAR, far, 0.0f);
  }
  explicit CameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Camera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Camera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Camera> CreateCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float fov = 0.0f,
    float near = 0.0f,
    float far = 0.0f) {
  CameraBuilder builder_(_fbb);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_fov(fov);
  return builder_.Finish();
}

struct MeshRenderer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshRendererBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESH = 4,
    VT_MATERIALS = 6
  };
  const Core::Serialization::Uuid *mesh() const {
    return GetStruct<const Core::Serialization::Uuid *>(VT_MESH);
  }
  const ::flatbuffers::Vector<const Core::Serialization::Uuid *> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Serialization::Uuid *> *>(VT_MATERIALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Core::Serialization::Uuid>(verifier, VT_MESH, 8) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           verifier.EndTable();
  }
};

struct MeshRendererBuilder {
  typedef MeshRenderer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mesh(const Core::Serialization::Uuid *mesh) {
    fbb_.AddStruct(MeshRenderer::VT_MESH, mesh);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Uuid *>> materials) {
    fbb_.AddOffset(MeshRenderer::VT_MATERIALS, materials);
  }
  explicit MeshRendererBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshRenderer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshRenderer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRenderer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Serialization::Uuid *mesh = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Uuid *>> materials = 0) {
  MeshRendererBuilder builder_(_fbb);
  builder_.add_materials(materials);
  builder_.add_mesh(mesh);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRendererDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Serialization::Uuid *mesh = nullptr,
    const std::vector<Core::Serialization::Uuid> *materials = nullptr) {
  auto materials__ = materials ? _fbb.CreateVectorOfStructs<Core::Serialization::Uuid>(*materials) : 0;
  return Core::Serialization::CreateMeshRenderer(
      _fbb,
      mesh,
      materials__);
}

inline bool VerifyComponentData(::flatbuffers::Verifier &verifier, const void *obj, ComponentData type) {
  switch (type) {
    case ComponentData_NONE: {
      return true;
    }
    case ComponentData_Camera: {
      auto ptr = reinterpret_cast<const Core::Serialization::Camera *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ComponentData_MeshRenderer: {
      auto ptr = reinterpret_cast<const Core::Serialization::MeshRenderer *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyComponentDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyComponentData(
        verifier,  values->Get(i), types->GetEnum<ComponentData>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_COMPONENT_CORE_SERIALIZATION_H_
