// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONTENT_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_CONTENT_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct Material;
struct MaterialBuilder;

struct Texture;
struct TextureBuilder;

struct SubMesh;
struct SubMeshBuilder;

struct Mesh;
struct MeshBuilder;

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_NAME = 4,
    VT_INT_VALUES = 6,
    VT_FLOAT_VALUES = 8,
    VT_VEC2_VALUES = 10,
    VT_VEC3_VALUES = 12,
    VT_VEC4_VALUES = 14,
    VT_TEXTURE2D_VALUES = 16
  };
  const ::flatbuffers::String *program_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *int_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *>(VT_INT_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *float_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *>(VT_FLOAT_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *vec2_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *>(VT_VEC2_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *vec3_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *>(VT_VEC3_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *vec4_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *>(VT_VEC4_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *texture2d_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *>(VT_TEXTURE2D_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_NAME) &&
           verifier.VerifyString(program_name()) &&
           VerifyOffset(verifier, VT_INT_VALUES) &&
           verifier.VerifyVector(int_values()) &&
           verifier.VerifyVectorOfTables(int_values()) &&
           VerifyOffset(verifier, VT_FLOAT_VALUES) &&
           verifier.VerifyVector(float_values()) &&
           verifier.VerifyVectorOfTables(float_values()) &&
           VerifyOffset(verifier, VT_VEC2_VALUES) &&
           verifier.VerifyVector(vec2_values()) &&
           verifier.VerifyVectorOfTables(vec2_values()) &&
           VerifyOffset(verifier, VT_VEC3_VALUES) &&
           verifier.VerifyVector(vec3_values()) &&
           verifier.VerifyVectorOfTables(vec3_values()) &&
           VerifyOffset(verifier, VT_VEC4_VALUES) &&
           verifier.VerifyVector(vec4_values()) &&
           verifier.VerifyVectorOfTables(vec4_values()) &&
           VerifyOffset(verifier, VT_TEXTURE2D_VALUES) &&
           verifier.VerifyVector(texture2d_values()) &&
           verifier.VerifyVectorOfTables(texture2d_values()) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_name(::flatbuffers::Offset<::flatbuffers::String> program_name) {
    fbb_.AddOffset(Material::VT_PROGRAM_NAME, program_name);
  }
  void add_int_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>> int_values) {
    fbb_.AddOffset(Material::VT_INT_VALUES, int_values);
  }
  void add_float_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>> float_values) {
    fbb_.AddOffset(Material::VT_FLOAT_VALUES, float_values);
  }
  void add_vec2_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>> vec2_values) {
    fbb_.AddOffset(Material::VT_VEC2_VALUES, vec2_values);
  }
  void add_vec3_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>> vec3_values) {
    fbb_.AddOffset(Material::VT_VEC3_VALUES, vec3_values);
  }
  void add_vec4_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>> vec4_values) {
    fbb_.AddOffset(Material::VT_VEC4_VALUES, vec4_values);
  }
  void add_texture2d_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>> texture2d_values) {
    fbb_.AddOffset(Material::VT_TEXTURE2D_VALUES, texture2d_values);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>> int_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>> float_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>> vec2_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>> vec3_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>> vec4_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>> texture2d_values = 0) {
  MaterialBuilder builder_(_fbb);
  builder_.add_texture2d_values(texture2d_values);
  builder_.add_vec4_values(vec4_values);
  builder_.add_vec3_values(vec3_values);
  builder_.add_vec2_values(vec2_values);
  builder_.add_float_values(float_values);
  builder_.add_int_values(int_values);
  builder_.add_program_name(program_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_name = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *int_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *float_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *vec2_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *vec3_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *vec4_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *texture2d_values = nullptr) {
  auto program_name__ = program_name ? _fbb.CreateString(program_name) : 0;
  auto int_values__ = int_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>(*int_values) : 0;
  auto float_values__ = float_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>(*float_values) : 0;
  auto vec2_values__ = vec2_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>(*vec2_values) : 0;
  auto vec3_values__ = vec3_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>(*vec3_values) : 0;
  auto vec4_values__ = vec4_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>(*vec4_values) : 0;
  auto texture2d_values__ = texture2d_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>(*texture2d_values) : 0;
  return Core::Serialization::CreateMaterial(
      _fbb,
      program_name__,
      int_values__,
      float_values__,
      vec2_values__,
      vec3_values__,
      vec4_values__,
      texture2d_values__);
}

struct Texture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WIDTH = 4,
    VT_HEIGHT = 6,
    VT_FORMAT = 8,
    VT_SIZE = 10,
    VT_DATA = 12
  };
  int32_t width() const {
    return GetField<int32_t>(VT_WIDTH, 0);
  }
  int32_t height() const {
    return GetField<int32_t>(VT_HEIGHT, 0);
  }
  int32_t format() const {
    return GetField<int32_t>(VT_FORMAT, 0);
  }
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<int32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_FORMAT, 4) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct TextureBuilder {
  typedef Texture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_width(int32_t width) {
    fbb_.AddElement<int32_t>(Texture::VT_WIDTH, width, 0);
  }
  void add_height(int32_t height) {
    fbb_.AddElement<int32_t>(Texture::VT_HEIGHT, height, 0);
  }
  void add_format(int32_t format) {
    fbb_.AddElement<int32_t>(Texture::VT_FORMAT, format, 0);
  }
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(Texture::VT_SIZE, size, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Texture::VT_DATA, data);
  }
  explicit TextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Texture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Texture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Texture> CreateTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t width = 0,
    int32_t height = 0,
    int32_t format = 0,
    int32_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  TextureBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_size(size);
  builder_.add_format(format);
  builder_.add_height(height);
  builder_.add_width(width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Texture> CreateTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t width = 0,
    int32_t height = 0,
    int32_t format = 0,
    int32_t size = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return Core::Serialization::CreateTexture(
      _fbb,
      width,
      height,
      format,
      size,
      data__);
}

struct SubMesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX_OFFSET = 4,
    VT_INDEX_COUNT = 6
  };
  uint32_t index_offset() const {
    return GetField<uint32_t>(VT_INDEX_OFFSET, 0);
  }
  uint32_t index_count() const {
    return GetField<uint32_t>(VT_INDEX_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct SubMeshBuilder {
  typedef SubMesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index_offset(uint32_t index_offset) {
    fbb_.AddElement<uint32_t>(SubMesh::VT_INDEX_OFFSET, index_offset, 0);
  }
  void add_index_count(uint32_t index_count) {
    fbb_.AddElement<uint32_t>(SubMesh::VT_INDEX_COUNT, index_count, 0);
  }
  explicit SubMeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubMesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubMesh> CreateSubMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index_offset = 0,
    uint32_t index_count = 0) {
  SubMeshBuilder builder_(_fbb);
  builder_.add_index_count(index_count);
  builder_.add_index_offset(index_offset);
  return builder_.Finish();
}

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_INDICES = 6,
    VT_SUB_MESHES = 8,
    VT_AABB = 10
  };
  const ::flatbuffers::Vector<const Core::Serialization::Vertex *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Serialization::Vertex *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *sub_meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *>(VT_SUB_MESHES);
  }
  const Core::Serialization::AABB *aabb() const {
    return GetStruct<const Core::Serialization::AABB *>(VT_AABB);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyOffset(verifier, VT_SUB_MESHES) &&
           verifier.VerifyVector(sub_meshes()) &&
           verifier.VerifyVectorOfTables(sub_meshes()) &&
           VerifyField<Core::Serialization::AABB>(verifier, VT_AABB, 4) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Vertex *>> vertices) {
    fbb_.AddOffset(Mesh::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(Mesh::VT_INDICES, indices);
  }
  void add_sub_meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>>> sub_meshes) {
    fbb_.AddOffset(Mesh::VT_SUB_MESHES, sub_meshes);
  }
  void add_aabb(const Core::Serialization::AABB *aabb) {
    fbb_.AddStruct(Mesh::VT_AABB, aabb);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Vertex *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>>> sub_meshes = 0,
    const Core::Serialization::AABB *aabb = nullptr) {
  MeshBuilder builder_(_fbb);
  builder_.add_aabb(aabb);
  builder_.add_sub_meshes(sub_meshes);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Core::Serialization::Vertex> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *sub_meshes = nullptr,
    const Core::Serialization::AABB *aabb = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Core::Serialization::Vertex>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  auto sub_meshes__ = sub_meshes ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::SubMesh>>(*sub_meshes) : 0;
  return Core::Serialization::CreateMesh(
      _fbb,
      vertices__,
      indices__,
      sub_meshes__,
      aabb);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_CONTENT_CORE_SERIALIZATION_H_
