// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATERIAL_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_MATERIAL_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct Material;
struct MaterialBuilder;

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_NAME = 4,
    VT_INT_VALUES = 6,
    VT_FLOAT_VALUES = 8,
    VT_VEC2_VALUES = 10,
    VT_VEC3_VALUES = 12,
    VT_VEC4_VALUES = 14,
    VT_TEXTURE2D_VALUES = 16
  };
  const ::flatbuffers::String *program_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *int_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *>(VT_INT_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *float_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *>(VT_FLOAT_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *vec2_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *>(VT_VEC2_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *vec3_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *>(VT_VEC3_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *vec4_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *>(VT_VEC4_VALUES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *texture2d_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *>(VT_TEXTURE2D_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_NAME) &&
           verifier.VerifyString(program_name()) &&
           VerifyOffset(verifier, VT_INT_VALUES) &&
           verifier.VerifyVector(int_values()) &&
           verifier.VerifyVectorOfTables(int_values()) &&
           VerifyOffset(verifier, VT_FLOAT_VALUES) &&
           verifier.VerifyVector(float_values()) &&
           verifier.VerifyVectorOfTables(float_values()) &&
           VerifyOffset(verifier, VT_VEC2_VALUES) &&
           verifier.VerifyVector(vec2_values()) &&
           verifier.VerifyVectorOfTables(vec2_values()) &&
           VerifyOffset(verifier, VT_VEC3_VALUES) &&
           verifier.VerifyVector(vec3_values()) &&
           verifier.VerifyVectorOfTables(vec3_values()) &&
           VerifyOffset(verifier, VT_VEC4_VALUES) &&
           verifier.VerifyVector(vec4_values()) &&
           verifier.VerifyVectorOfTables(vec4_values()) &&
           VerifyOffset(verifier, VT_TEXTURE2D_VALUES) &&
           verifier.VerifyVector(texture2d_values()) &&
           verifier.VerifyVectorOfTables(texture2d_values()) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_name(::flatbuffers::Offset<::flatbuffers::String> program_name) {
    fbb_.AddOffset(Material::VT_PROGRAM_NAME, program_name);
  }
  void add_int_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>> int_values) {
    fbb_.AddOffset(Material::VT_INT_VALUES, int_values);
  }
  void add_float_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>> float_values) {
    fbb_.AddOffset(Material::VT_FLOAT_VALUES, float_values);
  }
  void add_vec2_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>> vec2_values) {
    fbb_.AddOffset(Material::VT_VEC2_VALUES, vec2_values);
  }
  void add_vec3_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>> vec3_values) {
    fbb_.AddOffset(Material::VT_VEC3_VALUES, vec3_values);
  }
  void add_vec4_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>> vec4_values) {
    fbb_.AddOffset(Material::VT_VEC4_VALUES, vec4_values);
  }
  void add_texture2d_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>> texture2d_values) {
    fbb_.AddOffset(Material::VT_TEXTURE2D_VALUES, texture2d_values);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>> int_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>> float_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>> vec2_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>> vec3_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>> vec4_values = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>> texture2d_values = 0) {
  MaterialBuilder builder_(_fbb);
  builder_.add_texture2d_values(texture2d_values);
  builder_.add_vec4_values(vec4_values);
  builder_.add_vec3_values(vec3_values);
  builder_.add_vec2_values(vec2_values);
  builder_.add_float_values(float_values);
  builder_.add_int_values(int_values);
  builder_.add_program_name(program_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_name = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>> *int_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>> *float_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>> *vec2_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>> *vec3_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>> *vec4_values = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>> *texture2d_values = nullptr) {
  auto program_name__ = program_name ? _fbb.CreateString(program_name) : 0;
  auto int_values__ = int_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryInt>>(*int_values) : 0;
  auto float_values__ = float_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryFloat>>(*float_values) : 0;
  auto vec2_values__ = vec2_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec2>>(*vec2_values) : 0;
  auto vec3_values__ = vec3_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec3>>(*vec3_values) : 0;
  auto vec4_values__ = vec4_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryVec4>>(*vec4_values) : 0;
  auto texture2d_values__ = texture2d_values ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::MapEntryUuid>>(*texture2d_values) : 0;
  return Core::Serialization::CreateMaterial(
      _fbb,
      program_name__,
      int_values__,
      float_values__,
      vec2_values__,
      vec3_values__,
      vec4_values__,
      texture2d_values__);
}

inline const Core::Serialization::Material *GetMaterial(const void *buf) {
  return ::flatbuffers::GetRoot<Core::Serialization::Material>(buf);
}

inline const Core::Serialization::Material *GetSizePrefixedMaterial(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::Serialization::Material>(buf);
}

inline bool VerifyMaterialBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::Serialization::Material>(nullptr);
}

inline bool VerifySizePrefixedMaterialBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::Serialization::Material>(nullptr);
}

inline void FinishMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Material> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Material> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MATERIAL_CORE_SERIALIZATION_H_
