// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATERIALSERIALIZER_CORE_H_
#define FLATBUFFERS_GENERATED_MATERIALSERIALIZER_CORE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Core {

struct MaterialSerializer;
struct MaterialSerializerBuilder;

struct MaterialSerializer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialSerializerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXTURE_UUID = 4
  };
  const ::flatbuffers::String *texture_uuid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTURE_UUID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEXTURE_UUID) &&
           verifier.VerifyString(texture_uuid()) &&
           verifier.EndTable();
  }
};

struct MaterialSerializerBuilder {
  typedef MaterialSerializer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_texture_uuid(::flatbuffers::Offset<::flatbuffers::String> texture_uuid) {
    fbb_.AddOffset(MaterialSerializer::VT_TEXTURE_UUID, texture_uuid);
  }
  explicit MaterialSerializerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialSerializer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialSerializer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialSerializer> CreateMaterialSerializer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> texture_uuid = 0) {
  MaterialSerializerBuilder builder_(_fbb);
  builder_.add_texture_uuid(texture_uuid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialSerializer> CreateMaterialSerializerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *texture_uuid = nullptr) {
  auto texture_uuid__ = texture_uuid ? _fbb.CreateString(texture_uuid) : 0;
  return Core::CreateMaterialSerializer(
      _fbb,
      texture_uuid__);
}

inline const Core::MaterialSerializer *GetMaterialSerializer(const void *buf) {
  return ::flatbuffers::GetRoot<Core::MaterialSerializer>(buf);
}

inline const Core::MaterialSerializer *GetSizePrefixedMaterialSerializer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::MaterialSerializer>(buf);
}

inline bool VerifyMaterialSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::MaterialSerializer>(nullptr);
}

inline bool VerifySizePrefixedMaterialSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::MaterialSerializer>(nullptr);
}

inline void FinishMaterialSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MaterialSerializer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMaterialSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MaterialSerializer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MATERIALSERIALIZER_CORE_H_
