// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESHSERIALIZER_CORE_H_
#define FLATBUFFERS_GENERATED_MESHSERIALIZER_CORE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "BaseTypesSerializer_generated.h"

namespace Core {

struct SubMeshSerializer;
struct SubMeshSerializerBuilder;

struct MeshSerializer;
struct MeshSerializerBuilder;

struct SubMeshSerializer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubMeshSerializerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX_OFFSET = 4,
    VT_INDEX_COUNT = 6
  };
  uint32_t index_offset() const {
    return GetField<uint32_t>(VT_INDEX_OFFSET, 0);
  }
  uint32_t index_count() const {
    return GetField<uint32_t>(VT_INDEX_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct SubMeshSerializerBuilder {
  typedef SubMeshSerializer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index_offset(uint32_t index_offset) {
    fbb_.AddElement<uint32_t>(SubMeshSerializer::VT_INDEX_OFFSET, index_offset, 0);
  }
  void add_index_count(uint32_t index_count) {
    fbb_.AddElement<uint32_t>(SubMeshSerializer::VT_INDEX_COUNT, index_count, 0);
  }
  explicit SubMeshSerializerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubMeshSerializer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubMeshSerializer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubMeshSerializer> CreateSubMeshSerializer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index_offset = 0,
    uint32_t index_count = 0) {
  SubMeshSerializerBuilder builder_(_fbb);
  builder_.add_index_count(index_count);
  builder_.add_index_offset(index_offset);
  return builder_.Finish();
}

struct MeshSerializer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshSerializerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_INDICES = 6,
    VT_SUB_MESHES = 8,
    VT_AABB = 10
  };
  const ::flatbuffers::Vector<const Core::Base::Vertex *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Base::Vertex *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::SubMeshSerializer>> *sub_meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::SubMeshSerializer>> *>(VT_SUB_MESHES);
  }
  const Core::Base::AABB *aabb() const {
    return GetStruct<const Core::Base::AABB *>(VT_AABB);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyOffset(verifier, VT_SUB_MESHES) &&
           verifier.VerifyVector(sub_meshes()) &&
           verifier.VerifyVectorOfTables(sub_meshes()) &&
           VerifyField<Core::Base::AABB>(verifier, VT_AABB, 4) &&
           verifier.EndTable();
  }
};

struct MeshSerializerBuilder {
  typedef MeshSerializer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Base::Vertex *>> vertices) {
    fbb_.AddOffset(MeshSerializer::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(MeshSerializer::VT_INDICES, indices);
  }
  void add_sub_meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::SubMeshSerializer>>> sub_meshes) {
    fbb_.AddOffset(MeshSerializer::VT_SUB_MESHES, sub_meshes);
  }
  void add_aabb(const Core::Base::AABB *aabb) {
    fbb_.AddStruct(MeshSerializer::VT_AABB, aabb);
  }
  explicit MeshSerializerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshSerializer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshSerializer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshSerializer> CreateMeshSerializer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Base::Vertex *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::SubMeshSerializer>>> sub_meshes = 0,
    const Core::Base::AABB *aabb = nullptr) {
  MeshSerializerBuilder builder_(_fbb);
  builder_.add_aabb(aabb);
  builder_.add_sub_meshes(sub_meshes);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshSerializer> CreateMeshSerializerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Core::Base::Vertex> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    const std::vector<::flatbuffers::Offset<Core::SubMeshSerializer>> *sub_meshes = nullptr,
    const Core::Base::AABB *aabb = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Core::Base::Vertex>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  auto sub_meshes__ = sub_meshes ? _fbb.CreateVector<::flatbuffers::Offset<Core::SubMeshSerializer>>(*sub_meshes) : 0;
  return Core::CreateMeshSerializer(
      _fbb,
      vertices__,
      indices__,
      sub_meshes__,
      aabb);
}

inline const Core::MeshSerializer *GetMeshSerializer(const void *buf) {
  return ::flatbuffers::GetRoot<Core::MeshSerializer>(buf);
}

inline const Core::MeshSerializer *GetSizePrefixedMeshSerializer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::MeshSerializer>(buf);
}

inline bool VerifyMeshSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::MeshSerializer>(nullptr);
}

inline bool VerifySizePrefixedMeshSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::MeshSerializer>(nullptr);
}

inline void FinishMeshSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MeshSerializer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MeshSerializer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MESHSERIALIZER_CORE_H_
