// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESH_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_MESH_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct SubMesh;
struct SubMeshBuilder;

struct Mesh;
struct MeshBuilder;

struct SubMesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX_OFFSET = 4,
    VT_INDEX_COUNT = 6
  };
  uint32_t index_offset() const {
    return GetField<uint32_t>(VT_INDEX_OFFSET, 0);
  }
  uint32_t index_count() const {
    return GetField<uint32_t>(VT_INDEX_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct SubMeshBuilder {
  typedef SubMesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index_offset(uint32_t index_offset) {
    fbb_.AddElement<uint32_t>(SubMesh::VT_INDEX_OFFSET, index_offset, 0);
  }
  void add_index_count(uint32_t index_count) {
    fbb_.AddElement<uint32_t>(SubMesh::VT_INDEX_COUNT, index_count, 0);
  }
  explicit SubMeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubMesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubMesh> CreateSubMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index_offset = 0,
    uint32_t index_count = 0) {
  SubMeshBuilder builder_(_fbb);
  builder_.add_index_count(index_count);
  builder_.add_index_offset(index_offset);
  return builder_.Finish();
}

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_INDICES = 6,
    VT_SUB_MESHES = 8,
    VT_AABB = 10
  };
  const ::flatbuffers::Vector<const Core::Serialization::Vertex *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Serialization::Vertex *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *sub_meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *>(VT_SUB_MESHES);
  }
  const Core::Serialization::AABB *aabb() const {
    return GetStruct<const Core::Serialization::AABB *>(VT_AABB);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyOffset(verifier, VT_SUB_MESHES) &&
           verifier.VerifyVector(sub_meshes()) &&
           verifier.VerifyVectorOfTables(sub_meshes()) &&
           VerifyField<Core::Serialization::AABB>(verifier, VT_AABB, 4) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Vertex *>> vertices) {
    fbb_.AddOffset(Mesh::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(Mesh::VT_INDICES, indices);
  }
  void add_sub_meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>>> sub_meshes) {
    fbb_.AddOffset(Mesh::VT_SUB_MESHES, sub_meshes);
  }
  void add_aabb(const Core::Serialization::AABB *aabb) {
    fbb_.AddStruct(Mesh::VT_AABB, aabb);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Vertex *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::SubMesh>>> sub_meshes = 0,
    const Core::Serialization::AABB *aabb = nullptr) {
  MeshBuilder builder_(_fbb);
  builder_.add_aabb(aabb);
  builder_.add_sub_meshes(sub_meshes);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Core::Serialization::Vertex> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::SubMesh>> *sub_meshes = nullptr,
    const Core::Serialization::AABB *aabb = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Core::Serialization::Vertex>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  auto sub_meshes__ = sub_meshes ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::SubMesh>>(*sub_meshes) : 0;
  return Core::Serialization::CreateMesh(
      _fbb,
      vertices__,
      indices__,
      sub_meshes__,
      aabb);
}

inline const Core::Serialization::Mesh *GetMesh(const void *buf) {
  return ::flatbuffers::GetRoot<Core::Serialization::Mesh>(buf);
}

inline const Core::Serialization::Mesh *GetSizePrefixedMesh(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::Serialization::Mesh>(buf);
}

inline bool VerifyMeshBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::Serialization::Mesh>(nullptr);
}

inline bool VerifySizePrefixedMeshBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::Serialization::Mesh>(nullptr);
}

inline void FinishMeshBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Mesh> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::Mesh> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MESH_CORE_SERIALIZATION_H_
