// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESHRENDERERSERIALIZER_CORE_H_
#define FLATBUFFERS_GENERATED_MESHRENDERERSERIALIZER_CORE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "BaseTypesSerializer_generated.h"

namespace Core {

struct MeshRendererSerializer;
struct MeshRendererSerializerBuilder;

struct MeshRendererSerializer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshRendererSerializerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESH = 4,
    VT_MATERIALS = 6
  };
  const Core::Base::Uuid *mesh() const {
    return GetStruct<const Core::Base::Uuid *>(VT_MESH);
  }
  const ::flatbuffers::Vector<const Core::Base::Uuid *> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Base::Uuid *> *>(VT_MATERIALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Core::Base::Uuid>(verifier, VT_MESH, 8) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           verifier.EndTable();
  }
};

struct MeshRendererSerializerBuilder {
  typedef MeshRendererSerializer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mesh(const Core::Base::Uuid *mesh) {
    fbb_.AddStruct(MeshRendererSerializer::VT_MESH, mesh);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Base::Uuid *>> materials) {
    fbb_.AddOffset(MeshRendererSerializer::VT_MATERIALS, materials);
  }
  explicit MeshRendererSerializerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshRendererSerializer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshRendererSerializer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshRendererSerializer> CreateMeshRendererSerializer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Base::Uuid *mesh = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Base::Uuid *>> materials = 0) {
  MeshRendererSerializerBuilder builder_(_fbb);
  builder_.add_materials(materials);
  builder_.add_mesh(mesh);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshRendererSerializer> CreateMeshRendererSerializerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Base::Uuid *mesh = nullptr,
    const std::vector<Core::Base::Uuid> *materials = nullptr) {
  auto materials__ = materials ? _fbb.CreateVectorOfStructs<Core::Base::Uuid>(*materials) : 0;
  return Core::CreateMeshRendererSerializer(
      _fbb,
      mesh,
      materials__);
}

inline const Core::MeshRendererSerializer *GetMeshRendererSerializer(const void *buf) {
  return ::flatbuffers::GetRoot<Core::MeshRendererSerializer>(buf);
}

inline const Core::MeshRendererSerializer *GetSizePrefixedMeshRendererSerializer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::MeshRendererSerializer>(buf);
}

inline bool VerifyMeshRendererSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::MeshRendererSerializer>(nullptr);
}

inline bool VerifySizePrefixedMeshRendererSerializerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::MeshRendererSerializer>(nullptr);
}

inline void FinishMeshRendererSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MeshRendererSerializer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshRendererSerializerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::MeshRendererSerializer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MESHRENDERERSERIALIZER_CORE_H_
