// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESHRENDERER_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_MESHRENDERER_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"

namespace Core {
namespace Serialization {

struct MeshRenderer;
struct MeshRendererBuilder;

struct MeshRenderer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshRendererBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESH = 4,
    VT_MATERIALS = 6
  };
  const Core::Serialization::Uuid *mesh() const {
    return GetStruct<const Core::Serialization::Uuid *>(VT_MESH);
  }
  const ::flatbuffers::Vector<const Core::Serialization::Uuid *> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<const Core::Serialization::Uuid *> *>(VT_MATERIALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Core::Serialization::Uuid>(verifier, VT_MESH, 8) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           verifier.EndTable();
  }
};

struct MeshRendererBuilder {
  typedef MeshRenderer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mesh(const Core::Serialization::Uuid *mesh) {
    fbb_.AddStruct(MeshRenderer::VT_MESH, mesh);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Uuid *>> materials) {
    fbb_.AddOffset(MeshRenderer::VT_MATERIALS, materials);
  }
  explicit MeshRendererBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshRenderer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshRenderer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRenderer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Serialization::Uuid *mesh = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Core::Serialization::Uuid *>> materials = 0) {
  MeshRendererBuilder builder_(_fbb);
  builder_.add_materials(materials);
  builder_.add_mesh(mesh);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRendererDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Core::Serialization::Uuid *mesh = nullptr,
    const std::vector<Core::Serialization::Uuid> *materials = nullptr) {
  auto materials__ = materials ? _fbb.CreateVectorOfStructs<Core::Serialization::Uuid>(*materials) : 0;
  return Core::Serialization::CreateMeshRenderer(
      _fbb,
      mesh,
      materials__);
}

inline const Core::Serialization::MeshRenderer *GetMeshRenderer(const void *buf) {
  return ::flatbuffers::GetRoot<Core::Serialization::MeshRenderer>(buf);
}

inline const Core::Serialization::MeshRenderer *GetSizePrefixedMeshRenderer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Core::Serialization::MeshRenderer>(buf);
}

inline bool VerifyMeshRendererBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Core::Serialization::MeshRenderer>(nullptr);
}

inline bool VerifySizePrefixedMeshRendererBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Core::Serialization::MeshRenderer>(nullptr);
}

inline void FinishMeshRendererBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::MeshRenderer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshRendererBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Core::Serialization::MeshRenderer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_MESHRENDERER_CORE_SERIALIZATION_H_
