// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OBJECT_CORE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_OBJECT_CORE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Base_generated.h"
#include "Component_generated.h"

namespace Core {
namespace Serialization {

struct Object;
struct ObjectBuilder;

struct Object FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_UUID = 6,
    VT_COMPONENTS = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const Core::Serialization::Uuid *uuid() const {
    return GetStruct<const Core::Serialization::Uuid *>(VT_UUID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::Component>> *components() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::Component>> *>(VT_COMPONENTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<Core::Serialization::Uuid>(verifier, VT_UUID, 8) &&
           VerifyOffset(verifier, VT_COMPONENTS) &&
           verifier.VerifyVector(components()) &&
           verifier.VerifyVectorOfTables(components()) &&
           verifier.EndTable();
  }
};

struct ObjectBuilder {
  typedef Object Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Object::VT_NAME, name);
  }
  void add_uuid(const Core::Serialization::Uuid *uuid) {
    fbb_.AddStruct(Object::VT_UUID, uuid);
  }
  void add_components(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::Component>>> components) {
    fbb_.AddOffset(Object::VT_COMPONENTS, components);
  }
  explicit ObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Object> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Object>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Object> CreateObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const Core::Serialization::Uuid *uuid = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Core::Serialization::Component>>> components = 0) {
  ObjectBuilder builder_(_fbb);
  builder_.add_components(components);
  builder_.add_uuid(uuid);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Object> CreateObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const Core::Serialization::Uuid *uuid = nullptr,
    const std::vector<::flatbuffers::Offset<Core::Serialization::Component>> *components = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto components__ = components ? _fbb.CreateVector<::flatbuffers::Offset<Core::Serialization::Component>>(*components) : 0;
  return Core::Serialization::CreateObject(
      _fbb,
      name__,
      uuid,
      components__);
}

}  // namespace Serialization
}  // namespace Core

#endif  // FLATBUFFERS_GENERATED_OBJECT_CORE_SERIALIZATION_H_
